sdkversion: "3.5.0"
name: "vpn_compliancetest_js"
app_type: "rhoelements"
version: "1.0"
vendor: "rhomobile"
build: "release"
bbver: "4.6"
applog: "rholog.txt"
#capabilities:
#  - read_sdcard
#  - write_sdcard
#rhohub:
#  url: "https://appstaging.rhohub.com/api/v1/"
#connection:
#  proxy: "http://wwwgate0.mot.com:1080"
iphone:
  configuration: "Release"
  sdk: "iphoneos7.1"
  entitlements: ./production/Entitlements.plist
#  provisionprofile: "iOS Team Provisioning Profile"
#  production:
  codesignidentity: "iPhone Developer: Sunil Kumar (W8L77BLH6N)"
  BundleIdentifier: "com.rhomobile.vpncompliancetestjs"
  BundleURLScheme: "vpncompliancetestjs"
  extensions:
    - rhoconnect-client
    - audiocapture
    - mediaplayer
    - screenorientation
    - sensor
    - printing
    - printing_zebra
wp:
  productid: "88e69430-071c-0131-3d46-606720a825c8"
symbian:
  uid: "0xede7d59e"
android:
  version: "4.2.2"
  abis: [arm, x86]
  manifest_template: AndroidManifest.erb
  extensions:
    - rhoconnect-client
    - audiocapture
    - signature
    - barcode
    - indicators
    - cardreader
    - mediaplayer
    - screenorientation
    - sensor
    - printing
    - printing_zebra
wm:
#sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
 #sdk: "MC3000c50b (ARMV4I)"
  extensions:
    - rhoconnect-client
    - audiocapture
    - barcode
    - indicators
    - cardreader
    - mediaplayer
    - screenorientation
    - sensor
    - printing
    - printing_zebra
